name: Android Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: checkout
        id: check
        uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - run: chmod 777 ./gradlew

      - name: Build inrt template
        run: |
          ./gradlew inrt:assembleTemplate
          ls

      - name: Key base64 to file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_key.jks'
          fileDir: '/tmp/.android_key/'
          encodedString: ${{ secrets.ANDROID_KEY_BASE64 }}

      - name: Build App
        run: |
          ls  inrt/build/outputs/apk/template/release
          mv  inrt/build/outputs/apk/template/release/*.apk  app/src/main/assets/template.apk
          ls  app/src/main/assets
          ./gradlew app:assembleCommonRelease

      - name: Sign apk
        env:
          ANDROID_KS_PASS: ${{ secrets.ANDROID_KS_PASS }}
        run: |
          sudo apt install apksigner
          for file in app/build/outputs/apk/common/release/*-unsigned.apk; do
          filename="${file##*/}"
          filename="${filename%-unsigned.apk}.apk"
          echo "Signing ${filename}"
          apksigner sign --v4-signing-enabled false --ks /tmp/.android_key/android_key.jks --ks-pass env:ANDROID_KS_PASS --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} --out app/build/outputs/apk/common/release/${filename} ${file}
          done
          rm app/build/outputs/apk/common/release/*-unsigned.apk

#      - name: Upload apk to artifact 1
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-common-arm64-v8a-release.apk
#          path: app/build/outputs/apk/common/release/app-common-arm64-v8a-release.apk
#
#      - name: Upload apk to artifact 2
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-common-armeabi-v7a-release.apk
#          path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release.apk
#
#      - name: Upload apk to artifact 3
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-common-universal-release.apk
#          path: app/build/outputs/apk/common/release/app-common-universal-release.apk
#
#      - name: create-gh-release
#        uses: taiki-e/create-gh-release-action@v1
#        with:
#          changelog: CHANGELOG.md
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'app/build/outputs/apk/common/release/*.apk'
